### ISSUE TITLE
Cap StatsModels at 0.5

### ISSUE THREAD

**Issue by kleinschmidt** [lbittarello/Microeconometrics.jl#10]
StatsModels v0.6 is a breaking change: [https://discourse.julialang.org/t/psa-breaking-changes-in-statsmodels-v0-6-0-terms-2-0-son-of-terms/]

I'd submit a PR but I've forgotten how to cap things in a REQUIRE file :)

**Comment by lbittarello** [comment]
Thanks for the pull request! I'll work on adapting the package to the new version of StatsModels as soon as possible. I was waiting for a final version before getting to terms with it

**Comment by kleinschmidt** [comment]
Great, ping me if you have questions or run into problems!

**Comment by lbittarello** [comment]
@kleinschmidt: I have redesigned the package around the new StatsModels. The new implementation is cleaner (see [here](https://github.com/lbittarello/Microeconometrics.jl/blob/master/src/data/types.jl) and the last section [here](https://github.com/lbittarello/Microeconometrics.jl/blob/master/src/data/utils.jl)). We could easily port it into StatsModels as a generalization of `Formula` if there is any interest. Let me know.

**Comment by lbittarello** [comment]
JuliaStats/StatsModels.jl#21
