### ISSUE TITLE
Please provide an initial x for your Optim objectives

### ISSUE THREAD

**Issue by pkofod** [lbittarello/Microeconometrics.jl#5]
The style you use here https://github.com/lbittarello/Microeconometrics.jl/blob/master/src/estimation/logit.jl#L93 and other places is no longer valid. I suggest you seed your constructor
```
TwiceDifferentiable(f, g!, fg!, h!, β, eltype(β))
```
for now. The last positional argument `eltype(β)` shouldn't be there, that's a bug. I'll add the following constructor asap.
```
TwiceDifferentiable(f, g!, fg!, h!, β)
```

**Comment by pkofod** [comment]
Constructor version two should work now

**Comment by lbittarello** [comment]
Thanks for the warning!
